In [185]:
import numpy as np
import time

In [195]:
def LU(A):
    m = A.shape[1]
    U = A.copy()
    L = np.eye(m)
    for k in range(1,m):
        for j in range(k+1,m+1):
            L[j-1,k-1] = U[j-1,k-1]/U[k-1,k-1]
            U[j-1,(k-1):] = U[j-1,(k-1):] - L[j-1,k-1]*U[k-1,(k-1):]
    return L, U

In [196]:
A = np.array([[1e-20,1],[1,1]])
print(A)

[[1.e-20 1.e+00]
 [1.e+00 1.e+00]]


In [197]:
L,U = LU(A)

In [198]:
L

array([[1.e+00, 0.e+00],
       [1.e+20, 1.e+00]])

In [199]:
U

array([[ 1.e-20,  1.e+00],
       [ 0.e+00, -1.e+20]])

In [201]:
np.dot(L,U)-A

array([[ 0.,  0.],
       [ 0., -1.]])

In [281]:
def LU_pivot(A):
    m = A.shape[1]
    P = np.arange(0,m)
    U = A.copy()
    L = np.eye(m)
    for k in range(1,m):
        maxVal = abs(U[k-1,k-1])
        maxIndex = k-1
        for ii in range(k,m):
            if abs(U[ii,k-1])>maxVal:
                maxVal = abs(U[ii,k-1])
                maxIndex = ii
                
        
        if maxIndex != k-1:
            P[k-1],P[maxIndex] = P[maxIndex],P[k-1]
            U[(k-1),(k-1):],U[maxIndex,(k-1):] = np.copy(U[maxIndex,(k-1):]),np.copy(U[k-1,(k-1):]) 
            ## FIX ME!!!  HELP MAKE THIS CORRECT!
            L[(k-1),:(k-1)],L[(k-1),:maxIndex] =np.copy(L[(k-1),maxIndex:]),np.copy(L[(k-1),(k-1):])

            
        for j in range(k+1,m+1):
            L[j-1,k-1] = U[j-1,k-1]/U[k-1,k-1]
            U[j-1,(k-1):] = U[j-1,(k-1):] - L[j-1,k-1]*U[k-1,(k-1):]
    return L, U


In [282]:
A = np.array([[1e-20,1],[1,1]])
L,U = LU_pivot(A)


ValueError: could not broadcast input array from shape (2) into shape (1)

In [276]:
print(L)
print(U)
print(np.dot(L,U))

[[0.e+00 1.e+00]
 [1.e-20 0.e+00]]
[[1. 1.]
 [0. 1.]]
[[0.e+00 1.e+00]
 [1.e-20 1.e-20]]
