In [24]:
import numpy as np
import time
from scipy import linalg as la

In [25]:
def LU(A):
    m = A.shape[1]
    U = A.copy()
    L = np.eye(m)
    for k in range(1,m):
        for j in range(k+1,m+1):
            L[j-1,k-1] = U[j-1,k-1]/U[k-1,k-1]
            U[j-1,(k-1):] = U[j-1,(k-1):] - L[j-1,k-1]*U[k-1,(k-1):]
    return L, U

In [226]:
def LU_pivot(A):
    m = A.shape[1]
    U = np.copy(A)
    L = np.eye(m)
    P = np.eye(m)

    for k in range(1,m):
        LTemp = np.copy(L)
        UTemp = np.copy(U)
        maxVal = np.abs(U[k-1,k-1])
        maxIndex = k-1;
        for i in range(k,m):
            if np.abs(U[k-1,i]) > maxVal:
                maxVal = np.abs(U[k-1,i])
                maxIndex = i;
        if maxIndex!=k-1:
            P[maxIndex],P[k-1] = np.copy(P[k-1]) , np.copy(P[maxIndex])
            U[k-1,(k-1):], U[maxIndex,(k-1):] = UTemp[maxIndex,(k-1):], UTemp[k-1,(k-1):]
            L[k-1,:k-1], L[maxIndex,:(k-1)] = LTemp[maxIndex,:(k-1)],LTemp[k-1,:k-1]

            print(maxIndex)
   
        # Replace the above "for" loop with the outer product representation just in case.
        L[(k):,(k-1)] = U[(k):,k-1]/U[k-1,k-1]
        U[(k):,(k-1):] = U[(k):,(k-1):] - np.outer(L[(k):,k-1],U[k-1,(k-1):])
    
    return L, U, P

In [227]:
A = np.array([[2,1,1,0],[4,3,3,1],[8,7,9,5],[6,7,9,8]])
L,U,P = LU_pivot(A)
AA = L @ U
print(P.T@AA)
print(A)

[[2. 1. 1. 0.]
 [4. 3. 3. 1.]
 [8. 7. 9. 5.]
 [6. 7. 9. 8.]]
[[2 1 1 0]
 [4 3 3 1]
 [8 7 9 5]
 [6 7 9 8]]


In [217]:
AA

array([[8.  , 7.  , 9.  , 5.  ],
       [6.  , 6.25, 8.75, 7.75],
       [2.  , 1.75, 1.25, 0.25],
       [4.  , 3.5 , 3.5 , 1.5 ]])

In [210]:
L@U

array([[8.  , 7.  , 9.  , 5.  ],
       [6.  , 6.25, 8.75, 7.75],
       [2.  , 1.75, 1.25, 0.25],
       [4.  , 3.5 , 3.5 , 1.5 ]])

In [211]:
LL@UU

array([[ 8.00000000e+00,  7.00000000e+00,  9.00000000e+00,
         5.00000000e+00],
       [ 6.00000000e+00,  7.00000000e+00,  9.00000000e+00,
         8.00000000e+00],
       [ 4.00000000e+00,  3.00000000e+00,  3.00000000e+00,
         1.00000000e+00],
       [ 2.00000000e+00,  1.00000000e+00,  1.00000000e+00,
        -2.22044605e-16]])

In [212]:
print(L@U)

[[8.   7.   9.   5.  ]
 [6.   6.25 8.75 7.75]
 [2.   1.75 1.25 0.25]
 [4.   3.5  3.5  1.5 ]]


In [213]:
P

array([[0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.]])

In [214]:
P = np.eye(4,4)
P[0],P[2]=np.copy(P[2]),np.copy(P[0])
print(P)

[[0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 0. 1.]]


In [197]:
P@A

array([[8., 7., 9., 5.],
       [4., 3., 3., 1.],
       [2., 1., 1., 0.],
       [6., 7., 9., 8.]])

In [198]:
P

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [199]:
P

array([[0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [1., 0., 0., 0.],
       [0., 0., 0., 1.]])

In [229]:
x = np.linspace(-np.pi,np.pi,15)
s = x.T

In [234]:
x,s = np.meshgrid(x,s)

In [239]:
np.min(x+s)

-6.283185307179586

In [ ]:
for j in range()