In [3]:
import numpy as np
import time

In [66]:
def LU(A):
    m = A.shape[1]
    U = A.copy()
    L = np.eye(m)
    for k in range(1,m):
        for j in range(k+1,m+1):
            L[j-1,k-1] = U[j-1,k-1]/U[k-1,k-1]
            U[j-1,(k-1):] = U[j-1,(k-1):] - L[j-1,k-1]*U[k-1,(k-1):]
    return L, U

In [151]:
def LU_pivot(A):
    m,n = np.shape(A)
    U = np.copy(A)
    L = np.eye(m)
    P = np.arange(m)

    for k in range(0,n-1):
        maxVal = np.abs(U[k,k])
        maxIndex = k;
        for i in range(k+1,m-1):
            temp = np.abs(U[i,k])
            if temp > maxVal:
                maxVal = temp;
                maxIndex = i;
            if maxIndex!=k:
                P[maxIndex],P[k] = P[k],P[maxIndex]
                U[maxIndex,k:],U[k,k:]=np.copy(U[k,k:]),np.copy(U[maxIndex,k:])
                L[maxIndex,:k],L[k,:k] = np.copy(L[k,:k]),np.copy(L[maxIndex,:k])

        for i in range(j+1,m-1):
            L[i,j] = U[i,j]/U[j,j]
            U[i,(j):] = U[i,j:] - L[i,j]*U[j,j:]
            
        # Replace the above "for" loop with the outer product representation just in case.
        # L[(k+1):,k] = U[(k+1):,k]/U[k,k]
        # U[(k+1):,k:] = U[(k+1):,k:] - np.outer(L[(k+1):,k],U[k,k:])
    
    return L, U, P

In [152]:
A = np.array([[1,3,3],[1,4,3],[4,7,2]])
L,U,P = LU_pivot(A)
AA = L @ U
print(AA[P]-A)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
